import { DinamicDisclaimer } from '@/components/Disclaimer';
import { Providers } from '@/components/ThemeProvider';
import { Footer } from '@/components/common/footer/Footer';
import { Header } from '@/components/common/header/Header';
import { BeakerMicroIcon } from '@/components/icons/BeakerMicroIcon';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { envs } from '../../config/envs';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'indawoods store',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} flex min-h-[100dvh] flex-col bg-background text-primary`}>
        <Providers>
          <Header />
          <section className='w-full'>{children}</section>
          <Footer />
          <DinamicDisclaimer />
          {envs.MODE !== 'production' && (
            <p className='fixed bottom-0 right-0 m-4 flex h-fit w-fit gap-1 rounded-lg border border-border bg-background p-2'>
              <BeakerMicroIcon />
              <span className='text-xs capitalize'>{envs.MODE}</span>
            </p>
          )}
        </Providers>
      </body>
    </html>
  );
}
