import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import { AsideMenu } from '@/components/common/asideMenu/AsideMenu';
import { PropsWithChildren } from 'react';
import { createClient } from '../../utils/supabase/server';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'indawoods store',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang='en'>
      <body
        className={`${inter.className} flex min-h-[100dvh] bg-background text-primary`}>
        {user && <AsideMenu />}
        <main
          className={`${user && 'md:ml-[300px]'} ml-[80px] min-h-[100dvh] flex-1 bg-neutral-50 p-6`}>
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
