import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import { AsideMenu } from '@/components/common/asideMenu/AsideMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'indawoods store',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} flex min-h-screen bg-background text-primary`}>
        <AsideMenu />
        <main className='flex-1 bg-neutral-50 p-6'>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
